/// Headers which can be found in the archives generated by Ark
pub enum Header {
    /// the archive header which contains information
    /// about the archive and the files it is made up of
    Archive {
        total_files: usize,
        /// the current archive version, starts at 1 on creation,
        /// increases by 1 on each update
        version: usize,
    },
    /// the file header which contains information about a specific file
    File {
        name: String,
        /// the compression method used for this file
        method: u8,
        compressed_size: usize,
        decompressed_size: usize,
    }
}

impl Header {
    pub fn to_bytes(&self) -> Vec<u8> {
        let string = match self {
            Header::Archive { total_files, version } => {
                format!(
                    "files:{}\nver:{}",
                    total_files, version
                )
            },
            Header::File
            { name, method, compressed_size, decompressed_size } => {
                format!(
                    "name:{}\nmethod:{}\ncompressed:{}\ndecompressed:{}",
                    name, method, compressed_size, decompressed_size
                )
            }
        };
        string.into_bytes()
    }
}